### ISSUE TITLE
Missing 'faq_list:addinstance'

### ISSUE THREAD

**Issue by eduardokraus** [AGILEDROP/moodle-block_faq_list#12] opened 2024-11-23 17:56 UTC
Notice: Invalid get_string() identifier: 'faq_list:addinstance' or component 'block_faq_list'. Perhaps you are missing $string['faq_list:addinstance'] = ''; in /home/aulaemvideo.com.br/moodle/blocks/faq_list/lang/en/block_faq_list.php?
line 356 of /lib/classes/string_manager_standard.php: call to debugging()
line 7001 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 2735 of /lib/accesslib.php: call to get_string()
line 2511 of /lib/accesslib.php: call to get_capability_string()
line 118 of /admin/roles/classes/capability_table_base.php: call to get_capability_docs_link()
line 135 of /admin/roles/classes/capability_table_with_risks.php: call to core_role_capability_table_base->display()
line 708 of /admin/roles/classes/define_role_table_advanced.php: call to core_role_capability_table_with_risks->display()
line 261 of /admin/roles/define.php: call to core_role_define_role_table_advanced->display()

**Comment by agile-mark-l** [comment] 2024-11-28 13:03
This is a duplicate of issue #3

**Closed as completed by agile-mark-l** 2024-11-28 13:03 UTC
Labels: duplicate
